name: IntegrationTest
on:
  push:
    branches: [main]
    tags: [v*]
  pull_request:

jobs:
  downstream:
    name: ${{ matrix.package.repo }}/${{ matrix.package.group }}
    strategy:
      fail-fast: false
      matrix:
        package:
          - {user: SciML, repo: SimpleNonlinearSolve.jl, group: All}
          - {user: SciML, repo: NonlinearSolve.jl, group: All}
    uses: "SciML/.github/.github/workflows/downstream.yml@v1"
    with:
      owner: "${{ matrix.package.user }}"
      repo: "${{ matrix.package.repo }}"
      group: "${{ matrix.package.group }}"
    secrets: "inherit"
